Composition {
	CurrentTime = 87,
	RenderRange = { 0, 1000 },
	GlobalRange = { 0, 1000 },
	CurrentID = 312,
	HiQ = true,
	PlaybackUpdateMode = 0,
	Version = "Fusion Studio 18.1.3 build 7",
	SavedOutputs = 2,
	HeldTools = 0,
	DisabledTools = 0,
	LockedTools = 0,
	AudioOffset = 0,
	AutoRenderRange = true,
	Resumable = true,
	OutputClips = {
	},
	Tools = {
		Loader1 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/thatcher/Movies/A003C0083_20210906004753_0001.MOV",
					FormatID = "QuickTimeMovies",
					Length = 1305,
					Multiframe = true,
					TrimIn = 0,
					TrimOut = 1304,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 5,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 1304
				}
			},
			Inputs = {
				Depth = Input { Value = 5, },
				["Gamut.ColorSpaceNest"] = Input { Value = 1, },
				["Gamut.GammaSpaceNest"] = Input { Value = 1, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				["Clip1.QuickTimeMovies.Advanced"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 55, -16.5 } },
		},
		DCTLInterpreter1 = Fuse.DCTLInterpreter {
			CtrlWZoom = false,
			Inputs = {
				DCTLFile = Input { Value = "/Users/thatcher/coding/utility-dctls/Utilities/ACES Exposure.dctl", },
				ImageInput = Input {
					SourceOp = "Loader1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 55, 16.5 } },
		}
	},
	Frames = {
		{
			FrameTypeID = "ChildFrame",
			Mode = 3,
			LayoutPreset = 0,
			PresetName = "Default",
			Left = 0,
			Top = 27,
			Width = 1800,
			Height = 1047,
			ZoneInfo = {
				["!Right"] = {
				},
				["!Left"] = {
				},
				AuxLeft = { Expanded = true },
				Right = { Expanded = true, },
				Left = { Expanded = false, },
				AuxRight = { Expanded = true }
			},
			ViewInfo = {
				Viewer1 = { Show = true, RatioY = 0.01, RatioX = 1, },
				InnerLeft = {
				},
				MainSplit = {
					RatioX = 100,
					RatioY = 1.0010460251046,
				},
				CenterSplit = {
					RatioX = 1,
					RatioY = 100,
				},
				Viewer2 = { Show = false, RatioX = 1, RatioY = 0.01, MRU = 0, Adjust = true, },
				Comments = { Show = false },
				Time = { Show = true, RatioX = 100, },
				InnerColumns = {
					RatioX = 100,
					RatioY = 1.9989539748954,
				},
				Keyframes = { Show = false, },
				LayoutStrip = { Show = true, RatioX = 100, },
				Inspector = { Show = true, RatioY = 1, RatioX = 100, },
				InnerRight = {
				},
				Clips = { Show = false, },
				OuterColumns = {
					RatioX = 100,
					RatioY = 1,
				},
				Effects = { Show = false, },
				ActionStrip = { Show = true, RatioX = 100, },
				Metadata = { Show = false, },
				OuterLeft = {
				},
				ViewerSplit = {
					RatioX = 100,
					RatioY = 1,
				},
				Nodes = { Show = true, RatioY = 100, RatioX = 1, },
				OuterRight = {
					RatioY = 100,
					PixelX = 420,
				},
				MediaPool = { Show = false, },
				Spline = { Show = false, }
			},
			Views = ordered() {
				Effects = MultiView {
					Active = "EffectView",
					ViewList = ordered() {
						EffectView = "EffectView"
					},
				},
				Nodes = MultiView {
					Active = "FlowView",
					ViewList = ordered() {
						FlowView = "FlowView"
					},
					FlowView = FlowView {
						Flags = {
							AutoHideNavigator = true,
							GridSnap = true,
							PipesAlways = true,
							ShowHidden = true,
							AutoSnap = true,
							RemoveRouters = true
						},
						NavigatorSize = { 200, 140 },
						Direction = "Vertical",
						PipeStyle = "Orthogonal",
						RootScale = 1,
						RootOffset = { 162.667, 86.5756 }
					}
				},
				Keyframes = MultiView {
					Active = "TimelineView",
					ViewList = ordered() {
						TimelineView = "TimelineView"
					},
					TimelineView = TimelineView {
						TreeControlState = {
						},
						DisplayMode = "All Tools",
						ShowCurrentTimeTools = false,
						Filter = "Show All",
						ShowSelectedTools = false,
						ShowAnimatedToolsOnly = false,
						ShowEditBoxes = false,
						KeyFrameView = {
							Position = { Left = 232, Bottom = 320 },
							ScaleX = 2.14424951267057,
							OffsetX = -51.4619883040936,
							OffsetY = 0,
							AutoScaling = "scroll",
							AutoSnapTo = "frame",
							AutoSnapToGuidelines = false,
							GuidelinesGrabEnabled = true,
							GuidelinesSnapTo = "frame"
						},
						Spreadsheet = { LeftPos = 232, Visible = false }
					}
				},
				Spline = MultiView {
					Active = "SplineView",
					ViewList = ordered() {
						SplineView = "SplineEditorView"
					},
					SplineView = SplineEditorView {
						LeftPos = 264,
						ScaleX = 0.2,
						ScaleY = 0.00338983050847458,
						OffsetX = 53.2,
						OffsetY = 0,
						AutoScaling = "scroll",
						AutoSnapTo = "frame",
						AutoSnapToGuidelines = false,
						GuidelinesSnapTo = "frame",
						ShowKeyMarkers = false,
						IndependentHandles = false,
						ShowNonSplineModifiers = false,
						GuidelinesGrabEnabled = true,
						ShowOneToolOnly = false,
						ShowSelectedTools = false,
						ShowAllInputs = false,
						Filter = "Show All"
					}
				},
				Inspector = MultiView {
					Active = "Tools",
					ViewList = ordered() {
						Tools = "ControlView",
						Modifiers = "ModifierView"
					},
				},
				Viewer1 = MultiView {
					Active = "LeftView",
					ViewList = ordered() {
						LeftView = "PreviewContainer"
					},
				},
				Viewer2 = MultiView {
					Active = "RightView",
					ViewList = ordered() {
						RightView = "PreviewContainer"
					},
				},
				Time = "TimeView",
				ActionStrip = "ActionStripView",
				LayoutStrip = "LayoutStripView"
			},
			Layout = {
				{ ID = "LayoutStrip", FixedY = 36, Resolve = false, Flat = true },
				{
					{
						{ ID = "MediaPool", Fusion = false, RatioX = 1 },
						{ ID = "Effects", RatioX = 1 },
						Zone = "Left",
						Rows = 2,
						PaneID = "OuterLeft",
						PixelX = 420
					},
					{
						{
							{
								{ ID = "MediaPool", Fusion = false, RatioX = 1 },
								{ ID = "Effects", RatioX = 1 },
								PaneID = "InnerLeft",
								MaxViews = 1,
								PixelX = 420,
								Rows = 2,
								Zone = "!Left"
							},
							{
								{
									{ ID = "Viewer1", RatioY = 0.01, RatioX = 1 },
									{ ID = "Viewer2", RatioX = 1 },
									RatioY = 1,
									Columns = 2,
									PaneID = "ViewerSplit"
								},
								{ ID = "Time", FixedY = 83, Flat = true },
								RatioX = 1,
								Rows = 2
							},
							{
								{ ID = "Inspector", RatioY = 1 },
								{ ID = "Metadata", RatioY = 1, Fusion = false },
								PaneID = "InnerRight",
								MaxViews = 1,
								PixelX = 420,
								Rows = 2,
								Zone = "!Right"
							},
							RatioY = 2,
							Columns = 3,
							PaneID = "InnerColumns"
						},
						{ ID = "ActionStrip", FixedY = 50, Flat = true },
						{
							{ ID = "Nodes", RatioX = 1 },
							{ ID = "Spline", RatioX = 1 },
							{ ID = "Keyframes", RatioX = 1 },
							RatioY = 1,
							Columns = 3,
							PaneID = "MainSplit"
						},
						{ Fusion = false, ID = "Clips", LARGE_FixedY = 160, MEDIUM_FixedY = 138, SMALL_FixedY = 110 },
						RatioX = 1,
						Rows = 4,
						PaneID = "CenterSplit"
					},
					{
						{ ID = "Inspector", RatioY = 1 },
						{ ID = "Metadata", RatioY = 1, Fusion = false },
						Zone = "Right",
						Rows = 2,
						PaneID = "OuterRight",
						PixelX = 420
					},
					RatioY = 1,
					Columns = 3,
					PaneID = "OuterColumns"
				},
				RatioX = 1,
				Rows = 2,
				RatioY = 1
			},
			TopBar = {
				Left = { "Left", "MediaPool", "Effects", "Clips", "Nodes", "Console" },
				Right = { "Spline", "Keyframes", "Metadata", "Inspector", "Right" }
			}
		}
	},
	Prefs = {
		Comp = {
			Interactive = {
				Proxy = {
					Scale = 1,
					AutoScale = 1,
				},
			},
			AutoSave = {
				Delay = 300,
			},
			Views = {
				RightView = {
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "FusionViewLUT",
							FitMarginY = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							NearZ = 0
						}
					},
				},
				LeftView = {
					Viewer = {
					},
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "FusionViewLUT",
							FitMarginY = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							NearZ = 0
						}
					},
					SubView = {
						Enabled = true,
						Navigator = false,
						Magnifier = false,
						ID = "GLWaveformViewer",
						GLWaveformViewer = {
							AutoBounds = true,
							Layout = { -1208, 30, -30, 444 }
						},
						GL3DHistogramViewer = {
							AutoBounds = false,
							Layout = { -401, 15, -15, 500 }
						},
						["3DHistogram"] = {
							DrawStyles = 1,
							Proxy = 4
						}
					},
				},
				View1 = {
					PrevCtrlInactiveColor = 4278255360,
					FullScreen = false,
					PickH = 1,
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "FusionViewLUT",
							FitMarginY = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							NearZ = 0
						}
					},
					PrevCtrlActiveColor = 4278190335,
					AlwaysOnTop = true,
					PickW = 1
				},
			},
			Paths = {
				Map = {
				},
			},
			FrameFormat = {
				Name = "Ultra HD 2160",
				Width = 3840,
				Height = 2160,
				GuideRatio = 1.77777777777778,
				DepthFull = 3,
				DepthPreview = 3,
				DepthInteractive = 3,
			},
			LastFile = "/Users/thatcher/coding/utility-dctls/Utilities/DaVinci Tone Mapping.dctl",
			Unsorted = {
				RenderSettings = {
					Configs = {
					}
				}
			},
			FlowView = {
				Direction = 1,
				GridSnap = true,
				PipesOnTop = true,
				ShowHidden = true,
				PipeStyle = 0,
			},
			QuickTime = {
			}
		}
	},
}

